import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ConnectWallet from "@/components/Layout/ConnectWallet";
import MainProvider from "./Context";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

declare global {
  interface Window {
    ethereum: any;
  }
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainProvider>
          <div className="border-b-2 h-16 px-6 bg-card text-card-foreground shadow-sm flex justify-end items-center">
            <ConnectWallet />
          </div>
          {children}
          <Toaster />
        </MainProvider>
      </body>
    </html>
  );
}

